var searchData=
[
  ['uiactionsheet_28racsignalsupport_29',['UIActionSheet(RACSignalSupport)',['../category_u_i_action_sheet_07_r_a_c_signal_support_08.html',1,'']]],
  ['uialertview_28racsignalsupport_29',['UIAlertView(RACSignalSupport)',['../category_u_i_alert_view_07_r_a_c_signal_support_08.html',1,'']]],
  ['uiapplication_28extensions_29',['UIApplication(Extensions)',['../category_u_i_application_07_extensions_08.html',1,'']]],
  ['uibarbuttonitem_28extension_29',['UIBarButtonItem(Extension)',['../category_u_i_bar_button_item_07_extension_08.html',1,'']]],
  ['uibarbuttonitem_28raccommandsupport_29',['UIBarButtonItem(RACCommandSupport)',['../category_u_i_bar_button_item_07_r_a_c_command_support_08.html',1,'']]],
  ['uibutton_28extension_29',['UIButton(Extension)',['../category_u_i_button_07_extension_08.html',1,'']]],
  ['uibutton_28raccommandsupport_29',['UIButton(RACCommandSupport)',['../category_u_i_button_07_r_a_c_command_support_08.html',1,'']]],
  ['uibutton_28sdautolayoutbutton_29',['UIButton(SDAutoLayoutButton)',['../category_u_i_button_07_s_d_auto_layout_button_08.html',1,'']]],
  ['uibutton_28sdextention_29',['UIButton(SDExtention)',['../category_u_i_button_07_s_d_extention_08.html',1,'']]],
  ['uibutton_28webcache_29',['UIButton(WebCache)',['../category_u_i_button_07_web_cache_08.html',1,'']]],
  ['uibutton_28webcachedeprecated_29',['UIButton(WebCacheDeprecated)',['../category_u_i_button_07_web_cache_deprecated_08.html',1,'']]],
  ['uicollectionreusableview_28racsignalsupport_29',['UICollectionReusableView(RACSignalSupport)',['../category_u_i_collection_reusable_view_07_r_a_c_signal_support_08.html',1,'']]],
  ['uicollectionview_28mjrefresh_29',['UICollectionView(MJRefresh)',['../category_u_i_collection_view_07_m_j_refresh_08.html',1,'']]],
  ['uicollectionviewcontroller_28rmmultipleviewscontroller_29',['UICollectionViewController(RMMultipleViewsController)',['../category_u_i_collection_view_controller_07_r_m_multiple_views_controller_08.html',1,'']]],
  ['uicolor_28hex_29',['UIColor(Hex)',['../category_u_i_color_07_hex_08.html',1,'']]],
  ['uicolor_28kvncontrast_29',['UIColor(KVNContrast)',['../category_u_i_color_07_k_v_n_contrast_08.html',1,'']]],
  ['uicolor_28magic_29',['UIColor(Magic)',['../category_u_i_color_07_magic_08.html',1,'']]],
  ['uicolor_28xwadd_29',['UIColor(XWAdd)',['../category_u_i_color_07_x_w_add_08.html',1,'']]],
  ['uicontrol_28racsignalsupport_29',['UIControl(RACSignalSupport)',['../category_u_i_control_07_r_a_c_signal_support_08.html',1,'']]],
  ['uicontrol_28racsignalsupportprivate_29',['UIControl(RACSignalSupportPrivate)',['../category_u_i_control_07_r_a_c_signal_support_private_08.html',1,'']]],
  ['uid',['uid',['../interface_p_p_morder.html#acb65795ce8dd1b439f05bd1adecbf0c1',1,'PPMorder']]],
  ['uidatepicker_28racsignalsupport_29',['UIDatePicker(RACSignalSupport)',['../category_u_i_date_picker_07_r_a_c_signal_support_08.html',1,'']]],
  ['uidevice_28devicetype_29',['UIDevice(DeviceType)',['../category_u_i_device_07_device_type_08.html',1,'']]],
  ['uidevice_28tbnewsdkidentifieraddition_29',['UIDevice(TBNewSDKIdentifierAddition)',['../category_u_i_device_07_t_b_new_s_d_k_identifier_addition_08.html',1,'']]],
  ['uids',['uids',['../interface_w_b_s_d_k_app_recommend_request.html#ab2619231f3b600607b5d05fdf9144fa7',1,'WBSDKAppRecommendRequest']]],
  ['uifont_28extension_29',['UIFont(Extension)',['../category_u_i_font_07_extension_08.html',1,'']]],
  ['uigesturerecognizer_28racsignalsupport_29',['UIGestureRecognizer(RACSignalSupport)',['../category_u_i_gesture_recognizer_07_r_a_c_signal_support_08.html',1,'']]],
  ['uiidentifier',['UIIdentifier',['../interface_menu_model.html#a6e05e1ef39c0f009d4e35fcd7ec94778',1,'MenuModel::UIIdentifier()'],['../interface_f_n_tab_model.html#aa26fd056e8e87c3d54ee44a7b7822aa9',1,'FNTabModel::UIIdentifier()'],['../interface_j_m_hi_buy_home_a_d_model.html#a8c115705a0f60975fe8e8d76936850d3',1,'JMHiBuyHomeADModel::UIIdentifier()']]],
  ['uiimage_28extension_29',['UIImage(Extension)',['../category_u_i_image_07_extension_08.html',1,'']]],
  ['uiimage_28forcedecode_29',['UIImage(ForceDecode)',['../category_u_i_image_07_force_decode_08.html',1,'']]],
  ['uiimage_28gif_29',['UIImage(GIF)',['../category_u_i_image_07_g_i_f_08.html',1,'']]],
  ['uiimage_28kvnempty_29',['UIImage(KVNEmpty)',['../category_u_i_image_07_k_v_n_empty_08.html',1,'']]],
  ['uiimage_28kvnimageeffects_29',['UIImage(KVNImageEffects)',['../category_u_i_image_07_k_v_n_image_effects_08.html',1,'']]],
  ['uiimage_28multiformat_29',['UIImage(MultiFormat)',['../category_u_i_image_07_multi_format_08.html',1,'']]],
  ['uiimage_28screenshot_29',['UIImage(ScreenShot)',['../category_u_i_image_07_screen_shot_08.html',1,'']]],
  ['uiimagepickercontroller_28racsignalsupport_29',['UIImagePickerController(RACSignalSupport)',['../category_u_i_image_picker_controller_07_r_a_c_signal_support_08.html',1,'']]],
  ['uiimageview_28bxextension_29',['UIImageView(BXExtension)',['../category_u_i_image_view_07_b_x_extension_08.html',1,'']]],
  ['uiimageview_28highlightedwebcache_29',['UIImageView(HighlightedWebCache)',['../category_u_i_image_view_07_highlighted_web_cache_08.html',1,'']]],
  ['uiimageview_28highlightedwebcachedeprecated_29',['UIImageView(HighlightedWebCacheDeprecated)',['../category_u_i_image_view_07_highlighted_web_cache_deprecated_08.html',1,'']]],
  ['uiimageview_28webcache_29',['UIImageView(WebCache)',['../category_u_i_image_view_07_web_cache_08.html',1,'']]],
  ['uiimageview_28webcachedeprecated_29',['UIImageView(WebCacheDeprecated)',['../category_u_i_image_view_07_web_cache_deprecated_08.html',1,'']]],
  ['uilabel_28click_29',['UILabel(Click)',['../category_u_i_label_07_click_08.html',1,'']]],
  ['uilabel_28extension_29',['UILabel(Extension)',['../category_u_i_label_07_extension_08.html',1,'']]],
  ['uilabel_28mjrefresh_29',['UILabel(MJRefresh)',['../category_u_i_label_07_m_j_refresh_08.html',1,'']]],
  ['uilabel_28sdlabelautoresize_29',['UILabel(SDLabelAutoResize)',['../category_u_i_label_07_s_d_label_auto_resize_08.html',1,'']]],
  ['uin',['uin',['../interface_q_q_api_w_p_a_object.html#a745f5d4c523650485bb8dc4ce720a34b',1,'QQApiWPAObject::uin()'],['../interface_tencent_o_auth.html#a458a807948a610662b8dac4a7964b3cf',1,'TencentOAuth::uin()']]],
  ['uinavigationbar_28background_29',['UINavigationBar(Background)',['../category_u_i_navigation_bar_07_background_08.html',1,'']]],
  ['uinavigationcontroller_28fdfullscreenpopgesture_29',['UINavigationController(FDFullscreenPopGesture)',['../category_u_i_navigation_controller_07_f_d_fullscreen_pop_gesture_08.html',1,'']]],
  ['uirefreshcontrol_28raccommandsupport_29',['UIRefreshControl(RACCommandSupport)',['../category_u_i_refresh_control_07_r_a_c_command_support_08.html',1,'']]],
  ['uiscreen_28extension_29',['UIScreen(Extension)',['../category_u_i_screen_07_extension_08.html',1,'']]],
  ['uiscrollview_28_29',['UIScrollView()',['../category_u_i_scroll_view_07_08.html',1,'']]],
  ['uiscrollview_28additions_29',['UIScrollView(Additions)',['../category_u_i_scroll_view_07_additions_08.html',1,'']]],
  ['uiscrollview_28dznemptydataset_29',['UIScrollView(DZNEmptyDataSet)',['../category_u_i_scroll_view_07_d_z_n_empty_data_set_08.html',1,'']]],
  ['uiscrollview_28emptydataset_29',['UIScrollView(EmptyDataSet)',['../category_u_i_scroll_view_07_empty_data_set_08.html',1,'']]],
  ['uiscrollview_28magic_29',['UIScrollView(Magic)',['../category_u_i_scroll_view_07_magic_08.html',1,'']]],
  ['uiscrollview_28mjextension_29',['UIScrollView(MJExtension)',['../category_u_i_scroll_view_07_m_j_extension_08.html',1,'']]],
  ['uiscrollview_28mjrefresh_29',['UIScrollView(MJRefresh)',['../category_u_i_scroll_view_07_m_j_refresh_08.html',1,'']]],
  ['uiscrollview_28sdautocontentsize_29',['UIScrollView(SDAutoContentSize)',['../category_u_i_scroll_view_07_s_d_auto_content_size_08.html',1,'']]],
  ['uisegmentedcontrol_28racsignalsupport_29',['UISegmentedControl(RACSignalSupport)',['../category_u_i_segmented_control_07_r_a_c_signal_support_08.html',1,'']]],
  ['uislider_28racsignalsupport_29',['UISlider(RACSignalSupport)',['../category_u_i_slider_07_r_a_c_signal_support_08.html',1,'']]],
  ['uistepper_28racsignalsupport_29',['UIStepper(RACSignalSupport)',['../category_u_i_stepper_07_r_a_c_signal_support_08.html',1,'']]],
  ['uiswitch_28racsignalsupport_29',['UISwitch(RACSignalSupport)',['../category_u_i_switch_07_r_a_c_signal_support_08.html',1,'']]],
  ['uitableview_28mjrefresh_29',['UITableView(MJRefresh)',['../category_u_i_table_view_07_m_j_refresh_08.html',1,'']]],
  ['uitableview_28removeemptycell_29',['UITableView(RemoveEmptyCell)',['../category_u_i_table_view_07_remove_empty_cell_08.html',1,'']]],
  ['uitableview_28sdautotableviewcellheight_29',['UITableView(SDAutoTableViewCellHeight)',['../category_u_i_table_view_07_s_d_auto_table_view_cell_height_08.html',1,'']]],
  ['uitableviewcell_28racsignalsupport_29',['UITableViewCell(RACSignalSupport)',['../category_u_i_table_view_cell_07_r_a_c_signal_support_08.html',1,'']]],
  ['uitableviewcontroller_28rmmultipleviewscontroller_29',['UITableViewController(RMMultipleViewsController)',['../category_u_i_table_view_controller_07_r_m_multiple_views_controller_08.html',1,'']]],
  ['uitableviewcontroller_28sdtableviewcontrollerautocellheight_29',['UITableViewController(SDTableViewControllerAutoCellHeight)',['../category_u_i_table_view_controller_07_s_d_table_view_controller_auto_cell_height_08.html',1,'']]],
  ['uitableviewheaderfooterview_28racsignalsupport_29',['UITableViewHeaderFooterView(RACSignalSupport)',['../category_u_i_table_view_header_footer_view_07_r_a_c_signal_support_08.html',1,'']]],
  ['uitextfield_28racsignalsupport_29',['UITextField(RACSignalSupport)',['../category_u_i_text_field_07_r_a_c_signal_support_08.html',1,'']]],
  ['uitextview_28racsignalsupport_29',['UITextView(RACSignalSupport)',['../category_u_i_text_view_07_r_a_c_signal_support_08.html',1,'']]],
  ['uitextview_28racsignalsupportunavailable_29',['UITextView(RACSignalSupportUnavailable)',['../category_u_i_text_view_07_r_a_c_signal_support_unavailable_08.html',1,'']]],
  ['uiview_28additions_29',['UIView(Additions)',['../category_u_i_view_07_additions_08.html',1,'']]],
  ['uiview_28animationproperty_29',['UIView(AnimationProperty)',['../category_u_i_view_07_animation_property_08.html',1,'']]],
  ['uiview_28autolayout_29',['UIView(AutoLayout)',['../category_u_i_view_07_auto_layout_08.html',1,'']]],
  ['uiview_28click_29',['UIView(Click)',['../category_u_i_view_07_click_08.html',1,'']]],
  ['uiview_28debug_29',['UIView(Debug)',['../category_u_i_view_07_debug_08.html',1,'']]],
  ['uiview_28dznconstraintbasedlayoutextensions_29',['UIView(DZNConstraintBasedLayoutExtensions)',['../category_u_i_view_07_d_z_n_constraint_based_layout_extensions_08.html',1,'']]],
  ['uiview_28extension_29',['UIView(Extension)',['../category_u_i_view_07_extension_08.html',1,'']]],
  ['uiview_28frame_29',['UIView(Frame)',['../category_u_i_view_07_frame_08.html',1,'']]],
  ['uiview_28framechange_29',['UIView(FrameChange)',['../category_u_i_view_07_frame_change_08.html',1,'']]],
  ['uiview_28ibextension_29',['UIView(IBExtension)',['../category_u_i_view_07_i_b_extension_08.html',1,'']]],
  ['uiview_28iq_5fuiview_5fhierarchy_29',['UIView(IQ_UIView_Hierarchy)',['../category_u_i_view_07_i_q___u_i_view___hierarchy_08.html',1,'']]],
  ['uiview_28iqtoolbaraddition_29',['UIView(IQToolbarAddition)',['../category_u_i_view_07_i_q_toolbar_addition_08.html',1,'']]],
  ['uiview_28krevent_29',['UIView(KREvent)',['../category_u_i_view_07_k_r_event_08.html',1,'']]],
  ['uiview_28krlayout_29',['UIView(KRLayout)',['../category_u_i_view_07_k_r_layout_08.html',1,'']]],
  ['uiview_28mjextension_29',['UIView(MJExtension)',['../category_u_i_view_07_m_j_extension_08.html',1,'']]],
  ['uiview_28runtime_29',['UIView(Runtime)',['../category_u_i_view_07_runtime_08.html',1,'']]],
  ['uiview_28sdautoheightwidth_29',['UIView(SDAutoHeightWidth)',['../category_u_i_view_07_s_d_auto_height_width_08.html',1,'']]],
  ['uiview_28sdautolayout_29',['UIView(SDAutoLayout)',['../category_u_i_view_07_s_d_auto_layout_08.html',1,'']]],
  ['uiview_28sdchangeframe_29',['UIView(SDChangeFrame)',['../category_u_i_view_07_s_d_change_frame_08.html',1,'']]],
  ['uiview_28sdextension_29',['UIView(SDExtension)',['../category_u_i_view_07_s_d_extension_08.html',1,'']]],
  ['uiview_28sdlayoutextention_29',['UIView(SDLayoutExtention)',['../category_u_i_view_07_s_d_layout_extention_08.html',1,'']]],
  ['uiview_28setrect_29',['UIView(SetRect)',['../category_u_i_view_07_set_rect_08.html',1,'']]],
  ['uiview_28webcacheoperation_29',['UIView(WebCacheOperation)',['../category_u_i_view_07_web_cache_operation_08.html',1,'']]],
  ['uiviewcontroller_28additions_29',['UIViewController(Additions)',['../category_u_i_view_controller_07_additions_08.html',1,'']]],
  ['uiviewcontroller_28defaultproperymethod_29',['UIViewController(DefaultProperyMethod)',['../category_u_i_view_controller_07_default_propery_method_08.html',1,'']]],
  ['uiviewcontroller_28fdfullscreenpopgesture_29',['UIViewController(FDFullscreenPopGesture)',['../category_u_i_view_controller_07_f_d_fullscreen_pop_gesture_08.html',1,'']]],
  ['uiviewcontroller_28fdfullscreenpopgestureprivate_29',['UIViewController(FDFullscreenPopGesturePrivate)',['../category_u_i_view_controller_07_f_d_fullscreen_pop_gesture_private_08.html',1,'']]],
  ['uiviewcontroller_28magic_29',['UIViewController(Magic)',['../category_u_i_view_controller_07_magic_08.html',1,'']]],
  ['uiviewcontroller_28rmmultipleviewscontroller_29',['UIViewController(RMMultipleViewsController)',['../category_u_i_view_controller_07_r_m_multiple_views_controller_08.html',1,'']]],
  ['uiviewcontroller_28vtmagicprivate_29',['UIViewController(VTMagicPrivate)',['../category_u_i_view_controller_07_v_t_magic_private_08.html',1,'']]],
  ['uiwebview_28javascriptalert_29',['UIWebView(JavaScriptAlert)',['../category_u_i_web_view_07_java_script_alert_08.html',1,'']]],
  ['uiwindow_28iq_5fuiwindow_5fhierarchy_29',['UIWindow(IQ_UIWindow_Hierarchy)',['../category_u_i_window_07_i_q___u_i_window___hierarchy_08.html',1,'']]],
  ['umsbaeviewcontroller',['UMSBaeViewController',['../interface_u_m_s_bae_view_controller.html',1,'']]],
  ['umshareemailobject',['UMShareEmailObject',['../interface_u_m_share_email_object.html',1,'']]],
  ['umshareemotionobject',['UMShareEmotionObject',['../interface_u_m_share_emotion_object.html',1,'']]],
  ['umshareextendobject',['UMShareExtendObject',['../interface_u_m_share_extend_object.html',1,'']]],
  ['umsharefileobject',['UMShareFileObject',['../interface_u_m_share_file_object.html',1,'']]],
  ['umshareimageobject',['UMShareImageObject',['../interface_u_m_share_image_object.html',1,'']]],
  ['umsharemusicobject',['UMShareMusicObject',['../interface_u_m_share_music_object.html',1,'']]],
  ['umshareobject',['UMShareObject',['../interface_u_m_share_object.html',1,'']]],
  ['umsharesmsobject',['UMShareSmsObject',['../interface_u_m_share_sms_object.html',1,'']]],
  ['umsharevideoobject',['UMShareVideoObject',['../interface_u_m_share_video_object.html',1,'']]],
  ['umsharewebpageobject',['UMShareWebpageObject',['../interface_u_m_share_webpage_object.html',1,'']]],
  ['umsocial_5fauthorizewithuserinfo_3awithcompletionhandler_3a',['umSocial_AuthorizeWithUserInfo:withCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#ae1ebabde25fa467a8dbd3360c69f1cae',1,'UMSocialPlatformProvider -p::umSocial_AuthorizeWithUserInfo:withCompletionHandler:(NSDictionary *userInfo, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#ae1ebabde25fa467a8dbd3360c69f1cae',1,'UMSocialPlatformProvider -p::umSocial_AuthorizeWithUserInfo:withCompletionHandler:(NSDictionary *userInfo, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5fauthorizewithuserinfo_3awithviewcontroller_3awithcompletionhandler_3a',['umSocial_AuthorizeWithUserInfo:withViewController:withCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#a99c9538562ad13c437698eadbd8fe7c6',1,'UMSocialPlatformProvider -p::umSocial_AuthorizeWithUserInfo:withViewController:withCompletionHandler:(NSDictionary *userInfo, [withViewController] UIViewController *viewController, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#a99c9538562ad13c437698eadbd8fe7c6',1,'UMSocialPlatformProvider -p::umSocial_AuthorizeWithUserInfo:withViewController:withCompletionHandler:(NSDictionary *userInfo, [withViewController] UIViewController *viewController, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5fcancelauthwithcompletionhandler_3a',['umSocial_cancelAuthWithCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#acd16d08a46fd30b401adca83262cc586',1,'UMSocialPlatformProvider -p::umSocial_cancelAuthWithCompletionHandler:(UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#acd16d08a46fd30b401adca83262cc586',1,'UMSocialPlatformProvider -p::umSocial_cancelAuthWithCompletionHandler:(UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5fclearcachedata',['umSocial_clearCacheData',['../protocol_u_m_social_platform_provider_01-p.html#a0ed5acc40aa41283f7e5fb5a1ef7faa8',1,'UMSocialPlatformProvider -p::umSocial_clearCacheData()'],['../protocol_u_m_social_platform_provider_01-p.html#a0ed5acc40aa41283f7e5fb5a1ef7faa8',1,'UMSocialPlatformProvider -p::umSocial_clearCacheData()']]],
  ['umsocial_5fhandleopenurl_3a',['umSocial_handleOpenURL:',['../protocol_u_m_social_platform_provider_01-p.html#a5076903efac29b14aa957259fa554bd2',1,'UMSocialPlatformProvider -p::umSocial_handleOpenURL:(NSURL *url)'],['../protocol_u_m_social_platform_provider_01-p.html#a5076903efac29b14aa957259fa554bd2',1,'UMSocialPlatformProvider -p::umSocial_handleOpenURL:(NSURL *url)']]],
  ['umsocial_5fplatformsdkversion',['umSocial_PlatformSDKVersion',['../protocol_u_m_social_platform_provider_01-p.html#a03a01c52bd5f6689bf20c35760a4460b',1,'UMSocialPlatformProvider -p::umSocial_PlatformSDKVersion()'],['../protocol_u_m_social_platform_provider_01-p.html#a03a01c52bd5f6689bf20c35760a4460b',1,'UMSocialPlatformProvider -p::umSocial_PlatformSDKVersion()']]],
  ['umsocial_5frequestforuserprofilewithcompletionhandler_3a',['umSocial_RequestForUserProfileWithCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#a1d888890a07689a660523c8e9cb614d9',1,'UMSocialPlatformProvider -p::umSocial_RequestForUserProfileWithCompletionHandler:(UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#a1d888890a07689a660523c8e9cb614d9',1,'UMSocialPlatformProvider -p::umSocial_RequestForUserProfileWithCompletionHandler:(UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5frequestforuserprofilewithviewcontroller_3acompletion_3a',['umSocial_RequestForUserProfileWithViewController:completion:',['../protocol_u_m_social_platform_provider_01-p.html#a19f829db2b2d3c83f332556b3685e411',1,'UMSocialPlatformProvider -p::umSocial_RequestForUserProfileWithViewController:completion:(id currentViewController, [completion] UMSocialRequestCompletionHandler completion)'],['../protocol_u_m_social_platform_provider_01-p.html#a19f829db2b2d3c83f332556b3685e411',1,'UMSocialPlatformProvider -p::umSocial_RequestForUserProfileWithViewController:completion:(id currentViewController, [completion] UMSocialRequestCompletionHandler completion)']]],
  ['umsocial_5fsetappkey_3awithappsecret_3awithredirecturl_3a',['umSocial_setAppKey:withAppSecret:withRedirectURL:',['../protocol_u_m_social_platform_provider_01-p.html#a4591a33b9f6de5ff2a688fbb82e42d6b',1,'UMSocialPlatformProvider -p::umSocial_setAppKey:withAppSecret:withRedirectURL:(NSString *appKey, [withAppSecret] NSString *appSecret, [withRedirectURL] NSString *redirectURL)'],['../protocol_u_m_social_platform_provider_01-p.html#a4591a33b9f6de5ff2a688fbb82e42d6b',1,'UMSocialPlatformProvider -p::umSocial_setAppKey:withAppSecret:withRedirectURL:(NSString *appKey, [withAppSecret] NSString *appSecret, [withRedirectURL] NSString *redirectURL)']]],
  ['umsocial_5fsharewithobject_3awithcompletionhandler_3a',['umSocial_ShareWithObject:withCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#a23c57a8e07c351874d8b2bff217c3fd7',1,'UMSocialPlatformProvider -p::umSocial_ShareWithObject:withCompletionHandler:(UMSocialMessageObject *object, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#a23c57a8e07c351874d8b2bff217c3fd7',1,'UMSocialPlatformProvider -p::umSocial_ShareWithObject:withCompletionHandler:(UMSocialMessageObject *object, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5fsharewithobject_3awithviewcontroller_3awithcompletionhandler_3a',['umSocial_ShareWithObject:withViewController:withCompletionHandler:',['../protocol_u_m_social_platform_provider_01-p.html#aaee3cd0e221b820d92575edbbf198c52',1,'UMSocialPlatformProvider -p::umSocial_ShareWithObject:withViewController:withCompletionHandler:(UMSocialMessageObject *object, [withViewController] UIViewController *viewController, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)'],['../protocol_u_m_social_platform_provider_01-p.html#aaee3cd0e221b820d92575edbbf198c52',1,'UMSocialPlatformProvider -p::umSocial_ShareWithObject:withViewController:withCompletionHandler:(UMSocialMessageObject *object, [withViewController] UIViewController *viewController, [withCompletionHandler] UMSocialRequestCompletionHandler completionHandler)']]],
  ['umsocial_5fsupportedfeatures',['umSocial_SupportedFeatures',['../protocol_u_m_social_platform_provider_01-p.html#a76d1a85244d9f7d3407197fa8fcee200',1,'UMSocialPlatformProvider -p::umSocial_SupportedFeatures()'],['../protocol_u_m_social_platform_provider_01-p.html#a76d1a85244d9f7d3407197fa8fcee200',1,'UMSocialPlatformProvider -p::umSocial_SupportedFeatures()']]],
  ['umsocialauthresponse',['UMSocialAuthResponse',['../interface_u_m_social_auth_response.html',1,'']]],
  ['umsocialcloudviewconfig',['UMSocialCloudViewConfig',['../interface_u_m_social_cloud_view_config.html',1,'']]],
  ['umsocialcoreimageutils',['UMSocialCoreImageUtils',['../interface_u_m_social_core_image_utils.html',1,'']]],
  ['umsocialdatamanager',['UMSocialDataManager',['../interface_u_m_social_data_manager.html',1,'']]],
  ['umsocialglobal',['UMSocialGlobal',['../interface_u_m_social_global.html',1,'']]],
  ['umsocialhandleplatformtypedelegate_20_2dp',['UMSocialHandlePlatformTypeDelegate -p',['../protocol_u_m_social_handle_platform_type_delegate_01-p.html',1,'']]],
  ['umsocialhandler',['UMSocialHandler',['../interface_u_m_social_handler.html',1,'']]],
  ['umsocialhandler_28umsociallimit_29',['UMSocialHandler(UMSocialLimit)',['../category_u_m_social_handler_07_u_m_social_limit_08.html',1,'']]],
  ['umsocialhandlerconfig',['UMSocialHandlerConfig',['../interface_u_m_social_handler_config.html',1,'']]],
  ['umsocialhttpfactory',['UMSocialHttpFactory',['../interface_u_m_social_http_factory.html',1,'']]],
  ['umsocialimageutil',['UMSocialImageUtil',['../interface_u_m_social_image_util.html',1,'']]],
  ['umsocialimagewartermarkconfig',['UMSocialImageWarterMarkConfig',['../interface_u_m_social_image_warter_mark_config.html',1,'']]],
  ['umsocialmanager',['UMSocialManager',['../interface_u_m_social_manager.html',1,'']]],
  ['umsocialmessageobject',['UMSocialMessageObject',['../interface_u_m_social_message_object.html',1,'']]],
  ['umsocialplatformconfig',['UMSocialPlatformConfig',['../interface_u_m_social_platform_config.html',1,'']]],
  ['umsocialplatformitemviewconfig',['UMSocialPlatformItemViewConfig',['../interface_u_m_social_platform_item_view_config.html',1,'']]],
  ['umsocialplatformprovider_20_2dp',['UMSocialPlatformProvider -p',['../protocol_u_m_social_platform_provider_01-p.html',1,'']]],
  ['umsocialqqhandler',['UMSocialQQHandler',['../interface_u_m_social_q_q_handler.html',1,'']]],
  ['umsocialresponse',['UMSocialResponse',['../interface_u_m_social_response.html',1,'']]],
  ['umsocialsdkversion',['umSocialSDKVersion',['../interface_u_m_social_global.html#aec8751548bd2bced8ee8ed1556df4daf',1,'UMSocialGlobal::umSocialSDKVersion()'],['../interface_u_m_social_global.html#aec8751548bd2bced8ee8ed1556df4daf',1,'UMSocialGlobal::umSocialSDKVersion()']]],
  ['umsocialsharecancelcontrolconfig',['UMSocialShareCancelControlConfig',['../interface_u_m_social_share_cancel_control_config.html',1,'']]],
  ['umsocialsharecontainerconfig',['UMSocialShareContainerConfig',['../interface_u_m_social_share_container_config.html',1,'']]],
  ['umsocialshareeditviewcontroller',['UMSocialShareEditViewController',['../interface_u_m_social_share_edit_view_controller.html',1,'']]],
  ['umsocialshareemailobjectconfig',['UMSocialShareEmailObjectConfig',['../interface_u_m_social_share_email_object_config.html',1,'']]],
  ['umsocialshareemotionobjectconfig',['UMSocialShareEmotionObjectConfig',['../interface_u_m_social_share_emotion_object_config.html',1,'']]],
  ['umsocialshareextendobjectconfig',['UMSocialShareExtendObjectConfig',['../interface_u_m_social_share_extend_object_config.html',1,'']]],
  ['umsocialsharefileobjectconfig',['UMSocialShareFileObjectConfig',['../interface_u_m_social_share_file_object_config.html',1,'']]],
  ['umsocialshareimageobjectconfig',['UMSocialShareImageObjectConfig',['../interface_u_m_social_share_image_object_config.html',1,'']]],
  ['umsocialsharemenuviewdelegate_20_2dp',['UMSocialShareMenuViewDelegate -p',['../protocol_u_m_social_share_menu_view_delegate_01-p.html',1,'']]],
  ['umsocialsharemusicobjectconfig',['UMSocialShareMusicObjectConfig',['../interface_u_m_social_share_music_object_config.html',1,'']]],
  ['umsocialshareobjectconfig',['UMSocialShareObjectConfig',['../interface_u_m_social_share_object_config.html',1,'']]],
  ['umsocialsharepagecontrolconfig',['UMSocialSharePageControlConfig',['../interface_u_m_social_share_page_control_config.html',1,'']]],
  ['umsocialsharepagecontroldelegate_20_2dp',['UMSocialSharePageControlDelegate -p',['../protocol_u_m_social_share_page_control_delegate_01-p.html',1,'']]],
  ['umsocialsharepagegroupviewconfig',['UMSocialSharePageGroupViewConfig',['../interface_u_m_social_share_page_group_view_config.html',1,'']]],
  ['umsocialsharepagescrollviewconfig',['UMSocialSharePageScrollViewConfig',['../interface_u_m_social_share_page_scroll_view_config.html',1,'']]],
  ['umsocialsharepagescrollviewdelegate_20_2dp',['UMSocialSharePageScrollViewDelegate -p',['../protocol_u_m_social_share_page_scroll_view_delegate_01-p.html',1,'']]],
  ['umsocialshareresponse',['UMSocialShareResponse',['../interface_u_m_social_share_response.html',1,'']]],
  ['umsocialsharesmsobjectconfig',['UMSocialShareSmsObjectConfig',['../interface_u_m_social_share_sms_object_config.html',1,'']]],
  ['umsocialsharetextobjectconfig',['UMSocialShareTextObjectConfig',['../interface_u_m_social_share_text_object_config.html',1,'']]],
  ['umsocialsharetitleviewconfig',['UMSocialShareTitleViewConfig',['../interface_u_m_social_share_title_view_config.html',1,'']]],
  ['umsocialshareuiconfig',['UMSocialShareUIConfig',['../interface_u_m_social_share_u_i_config.html',1,'']]],
  ['umsocialsharevideoobjectconfig',['UMSocialShareVideoObjectConfig',['../interface_u_m_social_share_video_object_config.html',1,'']]],
  ['umsocialsharewebpageobjectconfig',['UMSocialShareWebpageObjectConfig',['../interface_u_m_social_share_webpage_object_config.html',1,'']]],
  ['umsocialsinahandler',['UMSocialSinaHandler',['../interface_u_m_social_sina_handler.html',1,'']]],
  ['umsocialsoauthviewcontroller',['UMSocialSOAuthViewController',['../interface_u_m_social_s_o_auth_view_controller.html',1,'']]],
  ['umsocialstringwartermarkconfig',['UMSocialStringWarterMarkConfig',['../interface_u_m_social_string_warter_mark_config.html',1,'']]],
  ['umsocialtask',['UMSocialTask',['../interface_u_m_social_task.html',1,'']]],
  ['umsocialtaskdelegate_20_2dp',['UMSocialTaskDelegate -p',['../protocol_u_m_social_task_delegate_01-p.html',1,'']]],
  ['umsocialtaskmanager',['UMSocialTaskManager',['../interface_u_m_social_task_manager.html',1,'']]],
  ['umsocialuimanager',['UMSocialUIManager',['../interface_u_m_social_u_i_manager.html',1,'']]],
  ['umsocialuiutility',['UMSocialUIUtility',['../interface_u_m_social_u_i_utility.html',1,'']]],
  ['umsocialuserinforesponse',['UMSocialUserInfoResponse',['../interface_u_m_social_user_info_response.html',1,'']]],
  ['umsocialwartermarkconfig',['UMSocialWarterMarkConfig',['../interface_u_m_social_warter_mark_config.html',1,'']]],
  ['umsocialwechathandler',['UMSocialWechatHandler',['../interface_u_m_social_wechat_handler.html',1,'']]],
  ['underline',['underLine',['../category_y_z_display_view_controller_07_08.html#a1a4fd8e7a434c68db46a98c8bcbf91a8',1,'YZDisplayViewController()']]],
  ['underlinecolor',['underLineColor',['../interface_y_z_display_view_controller.html#adec5ac1b84067893a1eef65121e82125',1,'YZDisplayViewController']]],
  ['underlineh',['underLineH',['../interface_y_z_display_view_controller.html#a1e9a2d9dda7aad55700b7f1eff4f873a',1,'YZDisplayViewController']]],
  ['uninstall',['uninstall',['../interface_m_a_s_constraint.html#a66e7e05283761f2e8b87bf597f9b607b',1,'MASConstraint']]],
  ['uninstall_3a',['uninstall:',['../interface_alibc_user_agent.html#a97408c5b7d051a854f5d83c14f492c47',1,'AlibcUserAgent']]],
  ['unionid',['unionid',['../interface_tencent_o_auth.html#a6641fb65b368515918f81edceba6e06e',1,'TencentOAuth']]],
  ['unitbezier',['UnitBezier',['../struct_web_core_1_1_unit_bezier.html',1,'WebCore']]],
  ['updatebounciness_3a',['updateBounciness:',['../category_p_o_p_animation_tracer_07_internal_08.html#a61998b16b4eb5df6d11dbd0bd269339c',1,'POPAnimationTracer(Internal)::updateBounciness:(float aFloat)'],['../category_p_o_p_animation_tracer_07_internal_08.html#a61998b16b4eb5df6d11dbd0bd269339c',1,'POPAnimationTracer(Internal)::updateBounciness:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a61998b16b4eb5df6d11dbd0bd269339c',1,'POPAnimationTracer::updateBounciness:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a61998b16b4eb5df6d11dbd0bd269339c',1,'POPAnimationTracer::updateBounciness:(float aFloat)']]],
  ['updateexisting',['updateExisting',['../interface_m_a_s_constraint_maker.html#ae2b84a526dbef016eb4cecccf7efe98d',1,'MASConstraintMaker::updateExisting()'],['../interface_m_a_s_constraint.html#aa3b903bceef8ceeb5c5f39d6b7690f3a',1,'MASConstraint::updateExisting()']]],
  ['updatefriction_3a',['updateFriction:',['../category_p_o_p_animation_tracer_07_internal_08.html#aba012bff58a203420d1adf3e922491e0',1,'POPAnimationTracer(Internal)::updateFriction:(float aFloat)'],['../category_p_o_p_animation_tracer_07_internal_08.html#aba012bff58a203420d1adf3e922491e0',1,'POPAnimationTracer(Internal)::updateFriction:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#aba012bff58a203420d1adf3e922491e0',1,'POPAnimationTracer::updateFriction:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#aba012bff58a203420d1adf3e922491e0',1,'POPAnimationTracer::updateFriction:(float aFloat)']]],
  ['updatefromvalue_3a',['updateFromValue:',['../category_p_o_p_animation_tracer_07_internal_08.html#aa5cc867da95a73d3254f38a86281233a',1,'POPAnimationTracer(Internal)::updateFromValue:(id aValue)'],['../category_p_o_p_animation_tracer_07_internal_08.html#aa5cc867da95a73d3254f38a86281233a',1,'POPAnimationTracer(Internal)::updateFromValue:(id aValue)'],['../interface_p_o_p_animation_tracer.html#aa5cc867da95a73d3254f38a86281233a',1,'POPAnimationTracer::updateFromValue:(id aValue)'],['../interface_p_o_p_animation_tracer.html#aa5cc867da95a73d3254f38a86281233a',1,'POPAnimationTracer::updateFromValue:(id aValue)']]],
  ['updatelayout',['updateLayout',['../category_u_i_view_07_s_d_auto_height_width_08.html#a8d81f0e5093a8917c4004c7e1e46ea11',1,'UIView(SDAutoHeightWidth)::updateLayout()'],['../category_u_i_view_07_s_d_auto_height_width_08.html#a8d81f0e5093a8917c4004c7e1e46ea11',1,'UIView(SDAutoHeightWidth)::updateLayout()'],['../category_u_i_view_07_s_d_auto_height_width_08.html#a8d81f0e5093a8917c4004c7e1e46ea11',1,'UIView(SDAutoHeightWidth)::updateLayout()']]],
  ['updatelayoutwithcellcontentview_3a',['updateLayoutWithCellContentView:',['../category_u_i_view_07_s_d_auto_height_width_08.html#ad0e71cc33b6b6cb7ad65236d0a8e5df9',1,'UIView(SDAutoHeightWidth)::updateLayoutWithCellContentView:(UIView *cellContentView)'],['../category_u_i_view_07_s_d_auto_height_width_08.html#ad0e71cc33b6b6cb7ad65236d0a8e5df9',1,'UIView(SDAutoHeightWidth)::updateLayoutWithCellContentView:(UIView *cellContentView)'],['../category_u_i_view_07_s_d_auto_height_width_08.html#ad0e71cc33b6b6cb7ad65236d0a8e5df9',1,'UIView(SDAutoHeightWidth)::updateLayoutWithCellContentView:(UIView *cellContentView)']]],
  ['updatemass_3a',['updateMass:',['../category_p_o_p_animation_tracer_07_internal_08.html#a1e41c2f1b7c5332730d2c834e0420367',1,'POPAnimationTracer(Internal)::updateMass:(float aFloat)'],['../category_p_o_p_animation_tracer_07_internal_08.html#a1e41c2f1b7c5332730d2c834e0420367',1,'POPAnimationTracer(Internal)::updateMass:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a1e41c2f1b7c5332730d2c834e0420367',1,'POPAnimationTracer::updateMass:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a1e41c2f1b7c5332730d2c834e0420367',1,'POPAnimationTracer::updateMass:(float aFloat)']]],
  ['updatemenutitles',['updateMenuTitles',['../interface_v_t_magic_view.html#a87cfe336988bf4d06aa52c3e1bbef132',1,'VTMagicView::updateMenuTitles()'],['../interface_v_t_magic_view.html#a87cfe336988bf4d06aa52c3e1bbef132',1,'VTMagicView::updateMenuTitles()'],['../interface_v_t_magic_view.html#a87cfe336988bf4d06aa52c3e1bbef132',1,'VTMagicView::updateMenuTitles()']]],
  ['updatenextpageproperties_3a',['updateNextPageProperties:',['../interface_u_t_tracker.html#ac9d1cca8b1fc2579aa0ad00c312f4188',1,'UTTracker']]],
  ['updateorderstatus',['updateOrderStatus',['../category_x_y_tab_bar_view_controller_07_08.html#af097c12f9b43d773f3d6fd0d407ace81',1,'XYTabBarViewController()::updateOrderStatus()'],['../interface_super_view_controller.html#a2ce67e1d8840d253941c3851d615fed8',1,'SuperViewController::updateOrderStatus()'],['../interface_a_d_super_view_controller.html#a8c7ad181e8405cfac84a53ae5c44d987',1,'ADSuperViewController::updateOrderStatus()']]],
  ['updatepagename_3apagename_3a',['updatePageName:pageName:',['../interface_u_t_tracker.html#af0b3ce3574a7cbf78cb880c567f9efa1',1,'UTTracker']]],
  ['updatepageproperties_3aproperties_3a',['updatePageProperties:properties:',['../interface_u_t_tracker.html#a302c0384d947b7d9b21dac1f66032206',1,'UTTracker']]],
  ['updatepagestatus_3astatus_3a',['updatePageStatus:status:',['../interface_u_t_tracker.html#adbe97e46febcc741a4f498f5511bc822',1,'UTTracker']]],
  ['updatepageurl_3aurl_3a',['updatePageUrl:url:',['../interface_u_t_tracker.html#a654369a4fe09d5c85726c32979be941f',1,'UTTracker']]],
  ['updateprogress_3aanimated_3a',['updateProgress:animated:',['../interface_k_v_n_progress.html#a70c537364b9ea751af24178448335b98',1,'KVNProgress::updateProgress:animated:(CGFloat progress, [animated] BOOL animated)'],['../interface_k_v_n_progress.html#a70c537364b9ea751af24178448335b98',1,'KVNProgress::updateProgress:animated:(CGFloat progress, [animated] BOOL animated)'],['../interface_k_v_n_progress.html#a70c537364b9ea751af24178448335b98',1,'KVNProgress::updateProgress:animated:(CGFloat progress, [animated] BOOL animated)']]],
  ['updateselecteditem',['updateSelectedItem',['../interface_v_t_menu_bar.html#afde29cf6a8858987b2c839de44455e4c',1,'VTMenuBar::updateSelectedItem()'],['../interface_v_t_menu_bar.html#afde29cf6a8858987b2c839de44455e4c',1,'VTMenuBar::updateSelectedItem()'],['../interface_v_t_menu_bar.html#afde29cf6a8858987b2c839de44455e4c',1,'VTMenuBar::updateSelectedItem()']]],
  ['updatespeed_3a',['updateSpeed:',['../category_p_o_p_animation_tracer_07_internal_08.html#a7f31ab4b95f8d9409a77b78bf7b8af1d',1,'POPAnimationTracer(Internal)::updateSpeed:(float aFloat)'],['../category_p_o_p_animation_tracer_07_internal_08.html#a7f31ab4b95f8d9409a77b78bf7b8af1d',1,'POPAnimationTracer(Internal)::updateSpeed:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a7f31ab4b95f8d9409a77b78bf7b8af1d',1,'POPAnimationTracer::updateSpeed:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a7f31ab4b95f8d9409a77b78bf7b8af1d',1,'POPAnimationTracer::updateSpeed:(float aFloat)']]],
  ['updatestatus_3a',['updateStatus:',['../interface_k_v_n_progress.html#ab50b37330761d25ce8b261290537da1a',1,'KVNProgress::updateStatus:(NSString *status)'],['../interface_k_v_n_progress.html#ab50b37330761d25ce8b261290537da1a',1,'KVNProgress::updateStatus:(NSString *status)'],['../interface_k_v_n_progress.html#ab50b37330761d25ce8b261290537da1a',1,'KVNProgress::updateStatus:(NSString *status)']]],
  ['updatetension_3a',['updateTension:',['../category_p_o_p_animation_tracer_07_internal_08.html#a5010bbc6fa2ec5426d33706651e584de',1,'POPAnimationTracer(Internal)::updateTension:(float aFloat)'],['../category_p_o_p_animation_tracer_07_internal_08.html#a5010bbc6fa2ec5426d33706651e584de',1,'POPAnimationTracer(Internal)::updateTension:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a5010bbc6fa2ec5426d33706651e584de',1,'POPAnimationTracer::updateTension:(float aFloat)'],['../interface_p_o_p_animation_tracer.html#a5010bbc6fa2ec5426d33706651e584de',1,'POPAnimationTracer::updateTension:(float aFloat)']]],
  ['updatetovalue_3a',['updateToValue:',['../category_p_o_p_animation_tracer_07_internal_08.html#a00d4c0e1b6b446081cfb6c153f37a633',1,'POPAnimationTracer(Internal)::updateToValue:(id aValue)'],['../category_p_o_p_animation_tracer_07_internal_08.html#a00d4c0e1b6b446081cfb6c153f37a633',1,'POPAnimationTracer(Internal)::updateToValue:(id aValue)'],['../interface_p_o_p_animation_tracer.html#a00d4c0e1b6b446081cfb6c153f37a633',1,'POPAnimationTracer::updateToValue:(id aValue)'],['../interface_p_o_p_animation_tracer.html#a00d4c0e1b6b446081cfb6c153f37a633',1,'POPAnimationTracer::updateToValue:(id aValue)']]],
  ['updatevelocity_3a',['updateVelocity:',['../category_p_o_p_animation_tracer_07_internal_08.html#ab828c06696377e94ba3bdd490b5cd146',1,'POPAnimationTracer(Internal)::updateVelocity:(id aValue)'],['../category_p_o_p_animation_tracer_07_internal_08.html#ab828c06696377e94ba3bdd490b5cd146',1,'POPAnimationTracer(Internal)::updateVelocity:(id aValue)'],['../interface_p_o_p_animation_tracer.html#ab828c06696377e94ba3bdd490b5cd146',1,'POPAnimationTracer::updateVelocity:(id aValue)'],['../interface_p_o_p_animation_tracer.html#ab828c06696377e94ba3bdd490b5cd146',1,'POPAnimationTracer::updateVelocity:(id aValue)']]],
  ['uploadpicresponse_3a',['uploadPicResponse:',['../protocol_tencent_session_delegate-p.html#ae464b20ef11dd5fbed06862bcbe2f7d2',1,'TencentSessionDelegate-p::uploadPicResponse:(APIResponse *response)'],['../protocol_tencent_session_delegate-p.html#ae464b20ef11dd5fbed06862bcbe2f7d2',1,'TencentSessionDelegate-p::uploadPicResponse:(APIResponse *response)']]],
  ['uploadpicwithparams_3a',['uploadPicWithParams:',['../interface_tencent_o_auth.html#a3345d746ba1bcdf4621a0fcc0a9f4237',1,'TencentOAuth::uploadPicWithParams:(NSMutableDictionary *params)'],['../interface_tencent_o_auth.html#a3345d746ba1bcdf4621a0fcc0a9f4237',1,'TencentOAuth::uploadPicWithParams:(NSMutableDictionary *params)']]],
  ['uri',['uri',['../interface_a_l_p_t_b_u_r_i_param.html#a6da79f0af540257717b7afd29a828d51',1,'ALPTBURIParam']]],
  ['url',['url',['../interface_w_b_http_request.html#ab14044463e9ed636ee593032460f1756',1,'WBHttpRequest::url()'],['../interface_open_webview_req.html#a2ea85dd46e252183bd14d075d41aa1b0',1,'OpenWebviewReq::url()'],['../interface_w_x_app_extend_object.html#aa83bdc98798add8efc102fdc45f28964',1,'WXAppExtendObject::url()'],['../interface_q_q_api_u_r_l_object.html#a5686a726251590a990115333ef704d1d',1,'QQApiURLObject::url()'],['../interface_u_m_share_extend_object.html#aaa43f6d63bb8ee3c37c4e644e9fe6052',1,'UMShareExtendObject::url()'],['../interface_a_l_b_b_custom_web_view_controller.html#adfa6dd7b8a4d0ee4f75220f573587ab2',1,'ALBBCustomWebViewController::url()'],['../interface_f_n_mine_function_model.html#a520d0ec969da6d01f0d89d8340fb9538',1,'FNMineFunctionModel::url()'],['../interface_j_m_invite_rule_controller.html#a557c07a3a07a76b8e8668f71ef9f7ed6',1,'JMInviteRuleController::url()'],['../interface_j_m_home_app_tie.html#ab0dfba661b8b3c15d0349c44bf79379b',1,'JMHomeAppTie::url()'],['../interface_f_n_web_view_controller.html#a4b40a192cf94637e4d50c3efde51042d',1,'FNWebViewController::url()'],['../interface_alibc_u_r_l_process_result.html#a4d8c755e124e49571bc92537eabe72ed',1,'AlibcURLProcessResult::URL()']]],
  ['urlcredential',['urlCredential',['../interface_s_d_web_image_downloader.html#adcc405c7347908892553755d566d25a5',1,'SDWebImageDownloader']]],
  ['urldecoded_3a',['urlDecoded:',['../interface_a_l_p_open_util.html#af5a7d624f1f1c4fc03ef437d358d1763',1,'ALPOpenUtil']]],
  ['urlmodel',['URLModel',['../interface_u_r_l_model.html',1,'URLModel'],['../category_top_mine_view_controller_07_08.html#a044bd08ca6680ca4a0b8fc3697d18dba',1,'TopMineViewController()::urlModel()']]],
  ['urlwithoutqueryandfragment_3a',['urlWithoutQueryAndFragment:',['../interface_alibc_u_r_l.html#af8b549ff1e1dfb5b236be3e3fd8d1dae',1,'AlibcURL']]],
  ['use_5fcoco2dx',['use_coco2dx',['../interface_u_m_social_global.html#a27539eecc2695b0c55836966a1834451',1,'UMSocialGlobal']]],
  ['usecellframecachewithindexpath_3atableview_3a',['useCellFrameCacheWithIndexPath:tableView:',['../category_u_i_view_07_s_d_auto_layout_08.html#a50e23f4176d2c7be1acae226cdc58703',1,'UIView(SDAutoLayout)::useCellFrameCacheWithIndexPath:tableView:(NSIndexPath *indexPath, [tableView] UITableView *tableview)'],['../category_u_i_view_07_s_d_auto_layout_08.html#a50e23f4176d2c7be1acae226cdc58703',1,'UIView(SDAutoLayout)::useCellFrameCacheWithIndexPath:tableView:(NSIndexPath *indexPath, [tableView] UITableView *tableview)'],['../category_u_i_view_07_s_d_auto_layout_08.html#a50e23f4176d2c7be1acae226cdc58703',1,'UIView(SDAutoLayout)::useCellFrameCacheWithIndexPath:tableView:(NSIndexPath *indexPath, [tableView] UITableView *tableview)']]],
  ['usedmoneylabel',['usedMoneyLabel',['../interface_dis_center_first_cell.html#a16f8f7ea88ee05ace8802008e2a73acc',1,'DisCenterFirstCell']]],
  ['usehttpcache',['useHTTPCache',['../interface_t_b_s_d_k_request.html#a53f701d77d4829f3ff576d0397ece4d5',1,'TBSDKRequest']]],
  ['usenavigationbarbuttonitemsofcurrentviewcontroller',['useNavigationBarButtonItemsOfCurrentViewController',['../interface_r_m_multiple_views_controller.html#ade7d30161846030d33fc0fa5ab09b5c9',1,'RMMultipleViewsController']]],
  ['user_5ftop_5fimg',['user_top_img',['../interface_profile_model.html#af7ab3b60129092798f302dd302d5bf6f',1,'ProfileModel']]],
  ['useralipay',['userAlipay',['../category_mine_view_controller_07_08.html#ac7cfce2bdeecc9e4c2255f184b5fd6e8',1,'MineViewController()']]],
  ['usercount',['userCount',['../interface_f_n_buy_product_model.html#ae856b5b22e9bfb1f90c93800194535b3',1,'FNBuyProductModel']]],
  ['userdata',['userData',['../interface_a_p_i_response.html#a74c4ca779214d1d867b2dbfcfc6085f0',1,'APIResponse']]],
  ['userid',['userID',['../interface_w_b_authorize_response.html#a235135bd60fde88c74ecfb877b9af0c9',1,'WBAuthorizeResponse::userID()'],['../interface_w_b_s_d_k_app_recommend_response.html#a3d45cebd15f2d640e7808d61509d90ed',1,'WBSDKAppRecommendResponse::userID()'],['../interface_j_m_member_display_model.html#a8dc251ec0a67a5251b6c71616dd31e67',1,'JMMemberDisplayModel::userid()'],['../interface_my_share_order_view_controller.html#adb607159bc35ae956d919c7c39d38330',1,'MyShareOrderViewController::userId()'],['../interface_fans_view_controller.html#a899cdc718e0fda339eb956a66a9cb89d',1,'FansViewController::userId()'],['../interface_follower_view_controller.html#afe4de0a5e6ca664b3ce604c6e636186d',1,'FollowerViewController::userId()']]],
  ['userimg',['userImg',['../category_mine_view_controller_07_08.html#a0509ccefafa426acd7acc107ef6a8de3',1,'MineViewController()']]],
  ['userinfo',['userInfo',['../interface_a_f_u_r_l_connection_operation.html#a118c5029a66496f6c9093a4e06d30faf',1,'AFURLConnectionOperation::userInfo()'],['../interface_w_b_data_transfer_object.html#ab9b7bf91e1470d29782202c04d1a86fe',1,'WBDataTransferObject::userInfo()']]],
  ['userinfomodel',['UserInfoModel',['../interface_user_info_model.html',1,'']]],
  ['userlevel',['userLevel',['../category_mine_view_controller_07_08.html#ae46b3ca7a1b87cac84cdd3c30fc1a1d1',1,'MineViewController()::userLevel()'],['../category_top_mine_view_controller_07_08.html#ac006d7859a88094a29d0a6d54b93c9ec',1,'TopMineViewController()::userLevel()']]],
  ['username',['userName',['../category_mine_view_controller_07_08.html#ae9a2aa12019845e498be05247cd2a0dd',1,'MineViewController()::userName()'],['../category_top_mine_view_controller_07_08.html#a538fda9fcd5ad654c4417204f69ce32c',1,'TopMineViewController()::userName()'],['../category_my_share_order_view_controller_07_08.html#a39b7ad5426dc02ef11769150a8c5d022',1,'MyShareOrderViewController()::userName()'],['../interface_s_d_web_image_downloader.html#a2d5ff61c6369936cafd3a74a936131cd',1,'SDWebImageDownloader::username()'],['../interface_open_temp_session_req.html#acf03474890a4c03bf442fbd97094931b',1,'OpenTempSessionReq::username()'],['../interface_jump_to_biz_profile_req.html#ad217e5e684d4db4977260fc8df38003b',1,'JumpToBizProfileReq::username()'],['../interface_f_n_phone_check_controller.html#a3690b40fd43181bd986390712771fa61',1,'FNPhoneCheckController::username()']]],
  ['userpicturecell',['UserPictureCell',['../interface_user_picture_cell.html',1,'']]],
  ['usetoolbaritemsofcurrentviewcontroller',['useToolbarItemsOfCurrentViewController',['../interface_r_m_multiple_views_controller.html#a11a162f4a0efb651a0c1566c44738eb9',1,'RMMultipleViewsController']]],
  ['ut',['UT',['../interface_u_t.html',1,'']]],
  ['utanalytics',['UTAnalytics',['../interface_u_t_analytics.html',1,'']]],
  ['utbaserequestauthentication',['UTBaseRequestAuthentication',['../interface_u_t_base_request_authentication.html',1,'']]],
  ['utcustomhitbuilder',['UTCustomHitBuilder',['../interface_u_t_custom_hit_builder.html',1,'']]],
  ['utdevice',['UTDevice',['../interface_u_t_device.html',1,'']]],
  ['utdid',['utdid',['../interface_u_t_device.html#a679ac9f6e75a769943db507089abb879',1,'UTDevice::utdid()'],['../interface_u_t_device.html#a679ac9f6e75a769943db507089abb879',1,'UTDevice::utdid()'],['../interface_alibc_config.html#a1fb8c04c3b4b902371a38994e3ca47ad',1,'AlibcConfig::utdId()']]],
  ['uthitbuilder',['UTHitBuilder',['../interface_u_t_hit_builder.html',1,'']]],
  ['uticrashcaughtlistener_20_2dp',['UTICrashCaughtListener -p',['../protocol_u_t_i_crash_caught_listener_01-p.html',1,'']]],
  ['utirequestauthentication_20_2dp',['UTIRequestAuthentication -p',['../protocol_u_t_i_request_authentication_01-p.html',1,'']]],
  ['utoirginalcustomhitbuilder',['UTOirginalCustomHitBuilder',['../interface_u_t_oirginal_custom_hit_builder.html',1,'']]],
  ['utpagehitbuilder',['UTPageHitBuilder',['../interface_u_t_page_hit_builder.html',1,'']]],
  ['utsecuritysdkrequestauthentication',['UTSecuritySDKRequestAuthentication',['../interface_u_t_security_s_d_k_request_authentication.html',1,'']]],
  ['uttracker',['UTTracker',['../interface_u_t_tracker.html',1,'']]]
];
